<?php
namespace WCTE;
defined('ABSPATH')||exit;
final class Frontend {
	private $b;private $r;private $t;private $service;
	public function __construct($b,$r,$t,$s){$this->b=$b;$this->r=$r;$this->t=$t;$this->service=$s;}
	public function hooks(){add_filter('query_vars',function($v){$v[]='wcte_token';return $v;});add_action('template_redirect',array($this,'redeem_page'));add_filter('woocommerce_account_menu_items',array($this,'menu'));add_action('woocommerce_account_training-enrollments_endpoint',array($this,'account'));}
	public function menu($items){$logout=$items['customer-logout']??null;unset($items['customer-logout']);$items['training-enrollments']=__('Training Enrollments','training-entitlements');if($logout)$items['customer-logout']=$logout;return $items;}
	public function redeem_page(){ $raw=get_query_var('wcte_token');if(!$raw)return;$batch=$this->b->by_token_hash($this->t->hash($raw));status_header(200);nocache_headers();get_header();echo '<main class="wcte-redemption" style="max-width:760px;margin:3rem auto;padding:1rem">';$valid=$this->service->validate($batch,get_current_user_id());$course=$batch?get_the_title($batch->course_id):'';echo '<h1>'.esc_html($course?:__('Training invitation','training-entitlements')).'</h1>';if($batch)echo '<p>'.esc_html(sprintf(__('Expires: %s','training-entitlements'),wp_date(get_option('date_format'),strtotime($batch->expires_at)))).'</p>';
		if(is_wp_error($valid)){echo '<div class="woocommerce-error">'.esc_html($valid->get_error_message()).'</div>';if(in_array($valid->get_error_code(),array('already_redeemed','already_enrolled'),true)&&$batch)echo '<p><a class="button" href="'.esc_url(get_permalink($batch->course_id)).'">'.esc_html__('Access course','training-entitlements').'</a></p>';}
		elseif(!is_user_logged_in()){ $return=$this->t->url($raw);echo '<p>'.esc_html__('Log in or create an account to redeem one enrollment.','training-entitlements').'</p><a class="button" href="'.esc_url(wp_login_url($return)).'">'.esc_html__('Log in','training-entitlements').'</a> ';if(function_exists('wc_get_page_permalink'))echo '<a class="button" href="'.esc_url(add_query_arg('redirect_to',rawurlencode($return),wc_get_page_permalink('myaccount'))).'">'.esc_html__('Create account','training-entitlements').'</a>';}
		elseif('POST'===$_SERVER['REQUEST_METHOD']&&isset($_POST['wcte_redeem'])){check_admin_referer('wcte_redeem_'.$batch->id);$result=$this->service->redeem($batch,get_current_user_id());if(is_wp_error($result))echo '<div class="woocommerce-error">'.esc_html($result->get_error_message()).'</div>';else echo '<div class="woocommerce-message">'.esc_html__('Enrollment successful.','training-entitlements').'</div><p><a class="button" href="'.esc_url(get_permalink($batch->course_id)).'">'.esc_html__('Access course','training-entitlements').'</a></p>';}
		else{echo '<form method="post">';wp_nonce_field('wcte_redeem_'.$batch->id);echo '<button class="button" name="wcte_redeem" value="1">'.esc_html__('Redeem enrollment','training-entitlements').'</button></form>';}echo '</main>';get_footer();exit;}
	public function account(){foreach($this->b->for_customer(get_current_user_id()) as $batch){$this->b->sync_status($batch->id);$batch=$this->b->find($batch->id);$order=wc_get_order($batch->order_id);echo '<section class="wcte-batch"><h3>'.esc_html(get_the_title($batch->course_id)).'</h3><p>'.esc_html(sprintf(__('Order #%1$s · Purchased %2$s · Expires %3$s','training-entitlements'),$order?$order->get_order_number():$batch->order_id,wp_date(get_option('date_format'),strtotime($batch->created_at)),wp_date(get_option('date_format'),strtotime($batch->expires_at)))).'</p><p><strong>'.esc_html(sprintf(__('%1$d of %2$d enrollments remaining','training-entitlements'),max(0,$batch->entitlements_total-$batch->entitlements_used),$batch->entitlements_total)).'</strong> — '.esc_html(ucfirst($batch->status)).'</p>';if('active'===$batch->status&&$order){$raw=$this->t->open($order->get_meta('_wcte_token_'.$batch->order_item_id));if($raw)echo '<p><button type="button" class="button wcte-copy" data-url="'.esc_attr($this->t->url($raw)).'">'.esc_html__('Copy Redemption Link','training-entitlements').'</button></p>';}echo '<table><thead><tr><th>'.esc_html__('Trainee','training-entitlements').'</th><th>'.esc_html__('Redeemed','training-entitlements').'</th></tr></thead><tbody>';foreach($this->r->for_batch($batch->id) as $red)echo '<tr><td>'.esc_html(trim($red->first_name_snapshot.' '.$red->last_name_snapshot)).'</td><td>'.esc_html(wp_date(get_option('date_format'),strtotime($red->redeemed_at))).'</td></tr>';echo '</tbody></table></section>';}echo '<script>document.querySelectorAll(".wcte-copy").forEach(b=>b.addEventListener("click",()=>navigator.clipboard.writeText(b.dataset.url)));</script>';}
}
