<?php
namespace WCTE;
defined('ABSPATH')||exit;
final class Admin {
	private $b;private $r;private $a;private $t;
	public function __construct($b,$r,$a,$t){$this->b=$b;$this->r=$r;$this->a=$a;$this->t=$t;}
	public function hooks(){add_action('admin_menu',array($this,'menu'));add_action('admin_post_wcte_batch_action',array($this,'action'));}
	public function menu(){add_submenu_page('woocommerce',__('Training Entitlements','training-entitlements'),__('Training Entitlements','training-entitlements'),'manage_woocommerce','wcte-batches',array($this,'page'));}
	public function page(){if(!current_user_can('manage_woocommerce'))wp_die(esc_html__('Unauthorized.','training-entitlements'));$status=isset($_GET['status'])?sanitize_key($_GET['status']):'';$search=isset($_GET['s'])?absint($_GET['s']):0;$where='1=1';$args=array();if($status){$where.=' AND status=%s';$args[]=$status;}if($search){$where.=' AND (id=%d OR order_id=%d OR subscription_id=%d OR customer_user_id=%d)';array_push($args,$search,$search,$search,$search);}$rows=$this->b->query($where,$args);echo '<div class="wrap"><h1>'.esc_html__('Training Entitlement Batches','training-entitlements').'</h1><form><input type="hidden" name="page" value="wcte-batches"><input name="s" type="search" value="'.esc_attr($search).'"><select name="status"><option value="">'.esc_html__('All statuses','training-entitlements').'</option>';foreach(array('active','exhausted','expired','revoked') as $s)echo '<option '.selected($status,$s,false).'>'.esc_html($s).'</option>';echo '</select><button class="button">'.esc_html__('Filter','training-entitlements').'</button></form><table class="widefat striped"><thead><tr><th>ID / Course</th><th>Customer / Source</th><th>Usage</th><th>Expiration / Status</th><th>Actions</th></tr></thead><tbody>';foreach($rows as $row){$url=admin_url('admin-post.php');echo '<tr><td>#'.esc_html($row->id).' '.esc_html(get_the_title($row->course_id)).'</td><td>User #'.esc_html($row->customer_user_id).'<br>Order #'.esc_html($row->order_id).($row->subscription_id?'<br>Subscription #'.esc_html($row->subscription_id):'').'</td><td>'.esc_html($row->entitlements_used.' / '.$row->entitlements_total).'</td><td>'.esc_html($row->expires_at.' · '.$row->status).'</td><td><form method="post" action="'.esc_url($url).'">';wp_nonce_field('wcte_admin_'.$row->id);echo '<input type="hidden" name="action" value="wcte_batch_action"><input type="hidden" name="batch_id" value="'.esc_attr($row->id).'"><select name="operation"><option value="revoke">Revoke</option><option value="reactivate">Reactivate</option><option value="regenerate">Regenerate token</option><option value="total">Change total</option><option value="expiration">Change expiration</option></select><input name="value" size="12" placeholder="value"><button class="button">Apply</button></form><details><summary>Roster</summary><ul>';foreach($this->r->for_batch($row->id) as $red)echo '<li>'.esc_html(trim($red->first_name_snapshot.' '.$red->last_name_snapshot).' — '.$red->redeemed_at).'</li>';echo '</ul></details></td></tr>';}echo '</tbody></table></div>';}
	public function action(){if(!current_user_can('manage_woocommerce'))wp_die('Unauthorized');$id=absint($_POST['batch_id']??0);check_admin_referer('wcte_admin_'.$id);$batch=$this->b->find($id);if(!$batch)wp_die('Not found');$op=sanitize_key($_POST['operation']??'');$value=sanitize_text_field(wp_unslash($_POST['value']??''));$data=array();$old='';$new='';if('revoke'===$op){$data['status']='revoked';$old=$batch->status;$new='revoked';}elseif('reactivate'===$op&&strtotime($batch->expires_at)>current_time('timestamp')){$data['status']=$batch->entitlements_used>=$batch->entitlements_total?'exhausted':'active';$old=$batch->status;$new=$data['status'];}elseif('total'===$op){$count=$this->r->completed_count($id);$total=absint($value);if($total<$count)wp_die('Total cannot be below completed redemptions.');$data['entitlements_total']=$total;$old=$batch->entitlements_total;$new=$total;}elseif('expiration'===$op){$date=date_create_immutable($value,wp_timezone());if(!$date)wp_die('Invalid date');$data['expires_at']=$date->format('Y-m-d H:i:s');$old=$batch->expires_at;$new=$data['expires_at'];}elseif('regenerate'===$op){$token=$this->t->generate();$data['token_hash']=$token['hash'];$order=wc_get_order($batch->order_id);if($order){$order->update_meta_data('_wcte_token_'.$batch->order_item_id,$this->t->seal($token['raw']));$order->save();}$old='invalidated';$new='regenerated';}else wp_die('Invalid action');$this->b->update($id,$data);$this->b->sync_status($id);$this->a->log($id,$op,$old,$new);wp_safe_redirect(admin_url('admin.php?page=wcte-batches'));exit;}
}
